### ISSUE TITLE
Failure to connect

### ISSUE THREAD

**Issue by kairoaraujo** [kairoaraujo/python-kodaksmarthome#3]
Seems they changed something I their portal :/

```
>>> my_home.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kairo/devel/python-kodaksmarthome/kodaksmarthome/api.py", line 314, in connect
    self._get_events()
  File "/Users/kairo/devel/python-kodaksmarthome/kodaksmarthome/api.py", line 280, in _get_events
    "GET", url_events, headers=HTTP_HEADERS_BASIC
  File "/Users/kairo/devel/python-kodaksmarthome/kodaksmarthome/api.py", line 155, in _http_request
    "Unexpected HTTP CODE error " + response_text
ConnectionError: Unexpected HTTP CODE error <!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>503 HTML Template by Ebuynow</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="css/style.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="Warning-404">
				<h3>Oops! Too many time click to page</h3>
				<h1><span>5</span><span>0</span><span>3</span></h1>
			</div>
			<h2>we are sorry, but you must wait several seconds to access again!</h2>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
```

**Comment by openWebX** [comment]
I forked and rewrote your code in php (https://github.com/openWebX/php-kodaksmarthome) and everything works as expected. So there must be a minor issue in your code, not at kodak's site. 
I'm not that good in python, but i will try to analyze the bug...

**Comment by openWebX** [comment]
OK, found the problem (i fixed it in php while debugging): You have to send the "JSESSIONID=xyz" in headers as "Cookie" for _get_devices and _get_events! Without the cookie explicitly set, you will get those connection errors...

**Comment by SimonScheerlynck** [comment]
Is there any plan to fix this?

**Comment by SimonScheerlynck** [comment]
Created a PR to attempt to fix this issue: https://github.com/kairoaraujo/python-kodaksmarthome/pull/9

**Comment by kairoaraujo** [comment]
That's great. I will review it :)

**Comment by kairoaraujo** [comment]
It is still happening to my account, but I will contact Kodak. But I see others using it :)
